import { createFileRoute } from "@tanstack/react-router";
import { Building2, Lock, MapPin } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/soul/AppShell";
import { Button } from "@/components/ui/button";
const cities=["Ibadan","Enugu","Kano","Port Harcourt","Abuja","Lagos","BS Island"];
const buildings=["Vault House","Empire Tower","Trade Nexus","Feast Hall","Iron Forge","Restoration Hall","Fortune Den","Vibe Temple","Enforcement Post","Judgment Seat","The Crucible","Soul Tower","Gang HQ","Crypto Exchange","Property Office","Pet Store","Card Altar","Chapel","Airdrop Tower","Bank Vault"];
export const Route=createFileRoute("/map")({ssr:false,head:()=>({meta:[{title:"World map — Soul Life"},{name:"description",content:"Explore cities, buildings and BS Island in Soul Life."},{property:"og:title",content:"World map — Soul Life"},{property:"og:description",content:"Explore a living Nigeria."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:MapPage});
function MapPage(){const[city,setCity]=useState("Ibadan");return <AppShell title="Your Nigeria" copy="Every city has a different economy, rhythm and opportunity."><div className="glass-card relative flex min-h-80 items-center justify-center overflow-hidden p-8"><div className="map-orbit"/><div className="relative text-center"><MapPin className="mx-auto h-12 w-12 text-primary"/><p className="mt-3 font-display text-4xl font-bold">{city}</p><p className="text-muted-foreground">Select a city to explore</p></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{cities.map(c=><Button key={c} className="glass-pill shrink-0 rounded-full" variant={city===c?"default":"outline"} onClick={()=>{if(c==="BS Island")toast.message("BS Island unlocks at Level 20");else setCity(c)}}>{c==="BS Island"&&<Lock/>}{c}</Button>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{buildings.map((b,i)=><button key={b} className="glass-card min-h-32 p-4 text-left transition-transform hover:-translate-y-1" onClick={()=>toast.success(`${b} selected in ${city}`)}><Building2 className="text-primary"/><p className="mt-5 font-semibold">{b}</p><p className="mt-1 text-xs text-muted-foreground">{i%3===0?"Open now":"Available in this city"}</p></button>)}</div></AppShell>}