import { createFileRoute } from "@tanstack/react-router";
import { Bell, CheckCheck, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { AppShell } from "@/components/soul/AppShell";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
type Note={id:string;title:string;body:string;is_read:boolean;created_at:string;category:string};
export const Route=createFileRoute("/notifications")({ssr:false,head:()=>({meta:[{title:"Notifications — Soul Life"},{name:"description",content:"Review your Soul Life alerts and updates."},{property:"og:title",content:"Notifications — Soul Life"},{property:"og:description",content:"Stay current with your empire."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Notifications});
function Notifications(){const{user}=useAuth();const[notes,setNotes]=useState<Note[]>([]);const load=async()=>{if(!user)return;const{data}=await supabase.from("notifications").select("id,title,body,is_read,created_at,category").order("created_at",{ascending:false});setNotes((data??[]) as Note[])};useEffect(()=>{void load()},[user]);const readAll=async()=>{if(!user)return;await supabase.from("notifications").update({is_read:true}).eq("user_id",user.id).eq("is_read",false);await load();toast.success("All caught up")};const clear=async()=>{if(!user)return;await supabase.from("notifications").delete().eq("user_id",user.id);await load();toast.success("Notifications cleared")};return <AppShell title="Notifications" copy="Everything that needs your attention, in one place."><div className="mb-5 flex flex-wrap gap-2"><Button className="glass-button" onClick={readAll}><CheckCheck/>Mark all read</Button><Button variant="outline" className="glass-button-ghost" onClick={clear}><Trash2/>Clear all</Button></div><div className="space-y-3">{notes.length===0?<div className="glass-card py-16 text-center"><Bell className="mx-auto h-10 w-10 text-primary"/><h2 className="mt-4 text-xl font-bold">You’re all caught up</h2><p className="mt-2 text-muted-foreground">New game, wallet and social updates will appear here.</p></div>:notes.map(n=><article key={n.id} className={`glass-card p-5 ${n.is_read?"opacity-70":"border-primary/50"}`} onClick={()=>{if(!n.is_read)void supabase.from("notifications").update({is_read:true}).eq("id",n.id).then(load)}}><div className="flex items-start gap-3"><Bell className="mt-1 text-primary"/><div><h2 className="font-bold">{n.title}</h2><p className="mt-1 text-sm text-muted-foreground">{n.body}</p><p className="mt-2 font-mono text-[10px] text-muted-foreground">{new Date(n.created_at).toLocaleString()}</p></div></div></article>)}</div></AppShell>}