import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Check, LoaderCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AuthShell } from "@/components/soul/AuthShell";
import { supabase } from "@/integrations/supabase/client";
import { usernameSchema } from "@/lib/validation";
const cities=["Ibadan","Enugu","Kano","Port Harcourt","Abuja","Lagos"];
export const Route=createFileRoute("/signup/profile")({ssr:false,head:()=>({meta:[{title:"Build your profile — Soul Life"},{name:"description",content:"Choose your Soul Life name and first Nigerian city."},{property:"og:title",content:"Build your profile — Soul Life"},{property:"og:description",content:"Choose your city and identity."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ProfileSetup});
function ProfileSetup(){const navigate=useNavigate();const[username,setUsername]=useState("");const[city,setCity]=useState("Ibadan");const[busy,setBusy]=useState(false);useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user)void navigate({to:"/login",search:{next:"/signup/profile"}})})},[navigate]);const save=async(e:React.FormEvent)=>{e.preventDefault();const p=usernameSchema.safeParse(username);if(!p.success)return toast.error(p.error.issues[0]?.message??"Choose another username");setBusy(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return navigate({to:"/login",search:{next:"/signup/profile"}})}const{data:taken}=await supabase.from("profiles").select("id").ilike("username",p.data).neq("id",user.id).maybeSingle();if(taken){setBusy(false);return toast.error("That username is taken")}const{error}=await supabase.from("profiles").upsert({id:user.id,email:user.email??sessionStorage.getItem("sl-signup-email")??"",username:p.data,whatsapp:sessionStorage.getItem("sl-signup-whatsapp"),city,habz:5000,vault:0,level:1,xp:0,soul_rating:0},{onConflict:"id"});setBusy(false);if(error)return toast.error(error.message);await navigate({to:"/signup/welcome"})};return <AuthShell eyebrow="CREATE YOUR SOUL" title="Choose where it begins." copy="Your name becomes your identity across every street, deal and leaderboard."><form onSubmit={save} className="space-y-5"><div><Input className="glass-input h-12" placeholder="Username" value={username} onChange={(e)=>setUsername(e.target.value)}/><p className="mt-2 text-xs text-muted-foreground">3–24 letters, numbers or underscores.</p></div><div><p className="mb-3 text-sm font-semibold">Starting city</p><div className="grid grid-cols-2 gap-2">{cities.map(c=><Button key={c} type="button" variant={city===c?"default":"outline"} className="h-auto min-h-12 whitespace-normal rounded-lg" onClick={()=>setCity(c)}>{city===c&&<Check/>}{c}</Button>)}</div></div><Button className="glass-button h-12 w-full" disabled={busy}>{busy&&<LoaderCircle className="animate-spin"/>}Create my Soul</Button></form></AuthShell>}