/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SignupProfileRouteImport } from './routes/signup.profile'
import { Route as SignupVerifyRouteImport } from './routes/signup.verify'
import { Route as SignupWelcomeRouteImport } from './routes/signup.welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupProfileRoute = SignupProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SignupRoute,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignupRoute,
} as any)
const SignupWelcomeRoute = SignupWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SignupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/notifications'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/profile': {
      id: '/signup/profile'
      path: '/profile'
      fullPath: '/signup/profile'
      preLoaderRoute: typeof SignupProfileRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/welcome': {
      id: '/signup/welcome'
      path: '/welcome'
      fullPath: '/signup/welcome'
      preLoaderRoute: typeof SignupWelcomeRouteImport
      parentRoute: typeof SignupRoute
    }
  }
}

interface SignupRouteChildren {
  SignupProfileRoute: typeof SignupProfileRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  SignupWelcomeRoute: typeof SignupWelcomeRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupProfileRoute: SignupProfileRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  SignupWelcomeRoute: SignupWelcomeRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
