/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GangsRouteImport } from './routes/gangs'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MarketRouteImport } from './routes/market'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SocialRouteImport } from './routes/social'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SignupProfileRouteImport } from './routes/signup.profile'
import { Route as SignupVerifyRouteImport } from './routes/signup.verify'
import { Route as SignupWelcomeRouteImport } from './routes/signup.welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GangsRoute = GangsRouteImport.update({
  id: '/gangs',
  path: '/gangs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupProfileRoute = SignupProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SignupRoute,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignupRoute,
} as any)
const SignupWelcomeRoute = SignupWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SignupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/market': typeof MarketRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/social': typeof SocialRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/profile': typeof SignupProfileRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/signup/welcome': typeof SignupWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/cards'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/market'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/social'
    | '/wallet'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arena'
    | '/cards'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/market'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/social'
    | '/wallet'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/cards'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/market'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/social'
    | '/wallet'
    | '/auth/callback'
    | '/signup/profile'
    | '/signup/verify'
    | '/signup/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaRoute: typeof ArenaRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GangsRoute: typeof GangsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MarketRoute: typeof MarketRoute
  NotificationsRoute: typeof NotificationsRoute
  PetsRoute: typeof PetsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRouteWithChildren
  SocialRoute: typeof SocialRoute
  WalletRoute: typeof WalletRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gangs': {
      id: '/gangs'
      path: '/gangs'
      fullPath: '/gangs'
      preLoaderRoute: typeof GangsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/profile': {
      id: '/signup/profile'
      path: '/profile'
      fullPath: '/signup/profile'
      preLoaderRoute: typeof SignupProfileRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/verify': {
      id: '/signup/verify'
      path: '/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/welcome': {
      id: '/signup/welcome'
      path: '/welcome'
      fullPath: '/signup/welcome'
      preLoaderRoute: typeof SignupWelcomeRouteImport
      parentRoute: typeof SignupRoute
    }
  }
}

interface SignupRouteChildren {
  SignupProfileRoute: typeof SignupProfileRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  SignupWelcomeRoute: typeof SignupWelcomeRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupProfileRoute: SignupProfileRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  SignupWelcomeRoute: SignupWelcomeRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaRoute: ArenaRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GangsRoute: GangsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MarketRoute: MarketRoute,
  NotificationsRoute: NotificationsRoute,
  PetsRoute: PetsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRouteWithChildren,
  SocialRoute: SocialRoute,
  WalletRoute: WalletRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
